### ISSUE TITLE
Scripts fron OpenRefine Lesson

### ISSUE THREAD

**Issue by ywharton** [datacarpentry/OpenRefine-ecology-lesson#102]
This may already be being worked on as part of the update, but what do people think of adding an additional dataset in this scripts lesson, to illustrate applying changes done in one project to another (possibly to a new seasons data? or a different animal). I'd estimate this should take 10 minutes as an exercise if they have already downloaded the file. This is in the lesson already - it might just strengthen the concept.

For example a scenario could be sharing your cleaning methodology with a collaborator (working on a different organism but collecting similar information?).  The .json file that learners export could then be applied to this new file imported as a new project. It also gives further practice open a new project. 

Happy to contribute this if people think it would be valuable.

**Comment by tracykteal** [comment]
Good idea! This would be great to add for the next release.

**Comment by villanueval** [comment]
This is a great idea. If anyone has an example to suggest in a PR, this would make it easier to check how it will work. Closing for now.
