### ISSUE TITLE
error in filtering exercise

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#109]
The first exercise (filtering) in https://github.com/datacarpentry/OpenRefine-ecology-lesson/blob/add-code-blocks/_episodes/02-filter-exclude-sort.md states that 48 rows should match the string "bai" in the `scientificName` column. However, if the learner has been following along in previous exercises, there is no single `scientificName` column, but rather two columns (for genus and species). Using the text filter "bai" on the genus gives 46 matches, and 2 in the species. I see that a subsequent question depends on the fact that the sting can match either genus or species so I propose two possible solutions:

1) Have the learner reverse the previous column split before completing this exercise (this is the simplest option).

or

2) Change the follow up exercise and have the learner filter only on the genus name. 

Any thoughts?

**Comment by tracykteal** [comment]
Option 1 sounds good, since it also demos an Undo,

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/127
