### ISSUE TITLE
use firefox as default browser for Windows users

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/OpenRefine-ecology-lesson#11]
A learner was using windows 10 and internet explorer. However, OpenRefine has some issues with internet explorer, so we should add a note in the installation instructions that learners may need to run openrefine from firefox (either by changing their default browser, or by opening firefox and go to http://127.0.0.1:3333)

**Comment by ErinBecker** [comment]
Not just a problem for Windows users. I'm on Mac El Capitan (10.11) using Chrome as my default browser and double-clicking openrefine icon does not launch GUI. I was just at a workshop where we used openrefine and they had the http link written on the whiteboard. Trying to use it now and had to dig through openrefine's github to find the link, but wouldn't have even known to look for it if I hadn't seen it at workshop.

This needs to get added to instructions or lesson is impossible for many users to do on their own and/or replicate post-workshop.

**Comment by fmichonneau** [comment]
Just to clarify, separate from the issue of having open refine launch automatically the browser pointing to the correct url, internet explorer and open refine don't go well together (I think some menus didn't show up, and some commands didn't get executed correctly).

**Comment by ErinBecker** [comment]
Thanks @fmichonneau. Appears to work in Chrome and Safari, but I'll do some more testing and update if I run into any problems.
