### ISSUE TITLE
sorting challenge is confusing

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#110]
In 02-filter-exclude-sort, the sorting challenge reads:

> ## Challenge
>
> Sort by month. How can you ensure that months are in order?
{: .challenge}

I think this is confusing for a couple of reasons. 

1) The learner may have another `sort` option already set on another column (based on following along in the exercise). We should explicitly tell them to select `sort by this column alone` and explain what that means.

2) It's unclear to me whether the intent of the challenge is to get every entry for January together, then every entry for February, etc, regardless of year. If that's the case, the learner will need to sort by number rather than date. If that's the intent, I think we could make the prompt more clear. E.g. "You would like to look for trends in your data by month of collection across years. How do you sort your data by month? How would you do this differently if you were instead trying to see all of your entries in chronological order?"

**Comment by tracykteal** [comment]
I like the wording in 2.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/127
