### ISSUE TITLE
recordID is factor?

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#112]
In 03-numbers.md it says, 

"To transform cells in the `recordID` column to numbers, click the down arrow for that column, then `Edit cells` > `Common transforms…` > `To number`. You will notice the `recordID` values change from left-justified to right-justified, and black to green color."

We should probably explain what type of data `recordID` was being represented as before transforming to numeric (and how we can tell).

**Comment by Repositorian** [comment]
My thought was to make the point at the beginning of the Open Refine lesson that the data coming in from the CSV will all be text by default, but that as the lesson progresses we will change those data formats and explore the consequences of doing so (maybe in Creating a Project?)

**Comment by ErinBecker** [comment]
@Repositorian - I agree. The way it's currently organized is a bit confusing because we have the learners changing data types before explaining that everything comes in as text. I think it's ok for this release, but after the lesson release a bit of reorganization of the explanatory parts would probably help. 

Closed with https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/112
