### ISSUE TITLE
Scatterplot facet section could be clearer

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#113]
The section in 03-numbers.md that discusses scatterplot facets showcases some interesting functionality but the plots are very difficult to make sense of (at least for me speaking as a non-ecologist who doesn't have an intuitive grasp on what "plot" or "period" means). This section could be improved with some screenshots and/or a more detailed explanation of how to read the plots.

**Comment by villanueval** [comment]
Added explanation of columns.
