### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#117]
In "working with OpenRefine", the link to "Getting Started with OpenRefine" at the top of the page goes to a 404 error.

**Comment by fmichonneau** [comment]
In case it's useful, I've used https://wummel.github.io/linkchecker/ to
check the links in the R lesson and it was great to find the broken links

**Comment by ErinBecker** [comment]
Thanks Francois!
