### ISSUE TITLE
installation issue on windows

### ISSUE THREAD

**Issue by ChristinaLK** [datacarpentry/OpenRefine-ecology-lesson#146]
We had an issue getting OpenRefine to run on a library Windows laptop; the fix ended up being to install Java (JDK + JRE) and add "JAVA_HOME" and "JDK_HOME" to the environment.  

Where could this information go?

**Comment by debpaul** [comment]
Hi @ChristinaLK. 

- From website: report any lesson errors or suggest improvements on GitHub or by email (admin@datacarpentry.org) 
- Put note here https://github.com/datacarpentry/OpenRefine-ecology-lesson/blob/gh-pages/_extras/guide.md
- I'm working on adding it to the above page - now.

**Comment by tracykteal** [comment]
Addressed by https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/148. Could still use some more information on how to add JAVA_HOME and JDK_HOME to path.

**Comment by ChristinaLK** [comment]
I'll note that to troubleshoot I ran the .bat file directly from the command prompt so that I could read the error messages. 

This link sort of points to the diagnosis: https://groups.google.com/forum/#!topic/openrefine/vUzqJqJ-sAA

I can't remember what page I used that showed how to set the JAVA_HOME + JRE_HOME variables. :P can try to look more tomorrow.
