### ISSUE TITLE
openrefine file types

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#15]
01-working-with-openrefine says: 

> Note the file types Open Refine handles: TSV, CSF, *SV, Excel (.xls .xlsx), JSON, XML, RDF as XML, Google Data documents. Support for other formats can be added with Google Refine extensions.  

I'm pretty sure "CSF" is meant to be "CSV". CSF is apparently used in Adobe for setting color settings. http://fileinfo.com/extension/csf

**Comment by tracykteal** [comment]
Solved by https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/38
