### ISSUE TITLE
OpenRefine algorithms in R

### ISSUE THREAD

**Issue by ChrisMuir** [datacarpentry/OpenRefine-ecology-lesson#154]
I have no idea if this would be helpful for use in this lesson (probably in "other resources"), but I developed an R package implementation of two of the OpenRefine clustering algorithms ([link](https://github.com/ChrisMuir/refinr) to GitHub page). The functions also utilize approximate string matching to catch minor misspellings, and the cluster merging is automated.

Anyways, figured I'd share. Feel free to use it if you'd like 😄

**Comment by ljvillanueva** [comment]
Valuable package for R, but outside the scope of the OpenRefine lesson. Thanks!

Closing.
