### ISSUE TITLE
Request for solution to Scatterplot facet exercise

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/OpenRefine-ecology-lesson#156]
Can you provide the solution to the Scatterplot facet exercise at http://www.datacarpentry.org/OpenRefine-ecology-lesson/03-numbers/?

> 1. Examine the scatterplots overall. Do the patterns make sense?
> 2. Why does the scatterplot for recordID vs period have the pattern it does?

**Comment by villanueval** [comment]
Questions were removed. They are asking about the data, not about working with data in OR.
