### ISSUE TITLE
Noting presence of OpenRefine preferences

### ISSUE THREAD

**Issue by nmwolf** [datacarpentry/OpenRefine-ecology-lesson#158]
There might be some use to noting the existence of the OpenRefine facet limit setting found under http://127.0.0.1:3333/preferences in the section 00:00 1 Introduction, under Features. Many years passed before somebody directed me to that most useful means of increasing one's facet choice size limit.

**Comment by hollyel** [comment]
Adding my support to your comment. My team and I have been working in OpenRefine for a while and struggling with the size of our data sets and number of facets not knowing this was an option. Thank you for posting this issue! That's a really important detail.

**Comment by villanueval** [comment]
This is a good suggestion, but I feel it falls outside the scope of an intro to OpenRefine. Plus, since there is not an option for this, it has to be entered as a variable, it is something new for the user to process, which is only useful for advanced use. Closing issue.
