### ISSUE TITLE
Leading-trailing whitespaces - no errors

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#16]
The section on splitting columns and removing leading/trailing whitespaces says: 

> This will reveal an error in a few names that have spaces at the beginning (so-called leading white space).  

Using this dataset, I saw no errors when I split the scientificName column. Following the instructions for removing the whitespace led to "text transform on 0 cells" for both new columns. If we want learners to actually see this error, need to add whitespaces to original file.

Coincidentally, the lesson notes say the Refine feature is "Remove leading and trailing whitespace", but as of version 2.6.beta .1, it's actually called "Trim leading and trailing whitespace".

**Comment by debpaul** [comment]
Hi @ErinBecker and thanks for your input to make these lessons better! Much appreciated. I'll be looking at these changes and merging them this week. Note there are white spaces (leading white spaces) in at least two names in the provided file. It's just that to "see" them, you have to click the edit button to see the leading white spaces. They are not obvious, but they are there. See   Amphispiza bilineata.
