### ISSUE TITLE
Introduce 'non-common' transforms as a concept

### ISSUE THREAD

**Issue by doortop** [datacarpentry/OpenRefine-ecology-lesson#161]
During the first episode, it might be useful to introduce how transforms not included in the 'common transforms' menu might be done. For example, we get questions all the time regarding cleaning data that could fall under 'Trimming' or 'Substrings' or 'Find and Replace'. I don't know if there is time to do an example (maybe to clean up Dipodomys�sp. in 'scientific name'), but just letting people know that the option is there, and let them know where to find the GREL functions, etc. (https://github.com/OpenRefine/OpenRefine/wiki/GREL-String-Functions)

**Comment by villanueval** [comment]
These transforms have been implemented in several updates. Closing as completed.
