### ISSUE TITLE
Date transformation

### ISSUE THREAD

**Issue by yshorish** [datacarpentry/OpenRefine-ecology-lesson#162]
I suggest incorporating date format transformations in the Number section of the lesson, or at the very end of the Sorting section. This could be done via GREL, reconciliation, or transformation and would probably add a minimum of 10 minutes on to the lesson, but is such a common issue in spreadsheet data that I think it is worth the cost. If something had to be removed from the lesson to make room, perhaps the section on Undo/Redo, since those operations do not behave out of the norm as you would find them in other programs.

**Comment by villanueval** [comment]
Closing as implemented.
