### ISSUE TITLE
Rewording on "Split Exercise"

### ISSUE THREAD

**Issue by valkcano26** [datacarpentry/OpenRefine-ecology-lesson#163]
During the "Working with Open Refine" > Split exercise.
Exercise involving the separator box.

 I think it should be clarified that when you delete the comma and replace with a space, that clicking on the space bar is needed. On a first pass people might just delete the comma and assume the blank space is there.

"3-In the pop-up, in the Separator box, replace the comma with a space"

I would include the words "click on space bar" to clarify, if they dont click on the space bar it creates an error.

**Comment by ljvillanueva** [comment]
Pull request merged. Thanks!
