### ISSUE TITLE
Clarification in the Introduction> Before we get Started

### ISSUE THREAD

**Issue by valkcano26** [datacarpentry/OpenRefine-ecology-lesson#164]
**2 Re-word suggestions in the Introduction:**

Possible Clarification needed on the section where it says :
I. 
"_Before we get started
Note: this is a Java program that runs on your machine (not in the cloud). It runs inside your browser, but no web connection is needed.
Follow the Setup instructions to install OpenRefine.
If after installation and running OpenRefine, it does not automatically open for you, point your browser at http://127.0.0.1:3333/ or http://localhost:3333 to launch the program_."

Referencing [this description](https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions)
We suggest more language that explains 
A- The application will open in your browser.
B- it runs as a small web server on your own computer and you point your web browser at that web server in order to use Refine. So, think of Refine as a personal and private web application.

**Suggested Language:
"Don't be surprised when the application opens in your browser, it is a desktop application that runs on your own computer, however, unlike most other desktop applications it runs as a small web server on your own computer and you point your web browser at that web server in order to use Refine.**"

II.
Also in the introduction we suggest emphasizing that the your "original data set is not modified" - in the key points for that page. - One of the advantages is you are not accidentally modifying your original data. - "**Imported Data is stored in Open Refines own format, therefore the original data file is left undisturbed"** - Additionally, this will get people thinking about when and where to export/ save their data throughout the process.

**Comment by tkphd** [comment]
1. **Suggested Language** for part 1 copies substantially from [OpenRefine.md](https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions) without attribution. How about this instead?
   > ## Before we get started
   > **OpenRefine** is a Java program that runs on your machine (not in the cloud): **it is a desktop application that uses your web browser as a graphical interface. No internet connection is needed, and none of the data or commands you enter in OpenRefine are sent to a remote server.**
   > 
   > Follow the Setup instructions to install OpenRefine. If after installation and running OpenRefine, it does not automatically open for you, point your browser at http://127.0.0.1:3333/ or http://localhost:3333 to launch the program.
2. The suggested phrasing for part 2 is unclear (OpenRefine's internal representation is independent of whether it writes back to the original file). How about this?
   > ## Motivations for the OpenRefine Lesson
   > - It is important to know what you did to your data. Additionally, journals, granting agencies, and other institutions are requiring documentation of the steps you took when working with your data. With OpenRefine, you can capture all actions applied to your raw data and share them with your publication as supplemental material.
   > - **You *must* export your modified dataset to a new file: OpenRefine does not write back into your original sources. If you don't save it, your OpenRefine work will be lost.**
   > - Any operation that changes the data in OpenRefine can be easily reversed or undone.
   > - Data is often very messy, and this tool saves a lot of time on cleaning headaches.
   > - Data cleaning steps often need repeating with multiple files. OpenRefine is perfect 
   >   for speeding up repetitive tasks by replaying previous actions on multiple datasets.
   > - Some concepts such as clustering algorithms are quite complex, but OpenRefine 
   >   makes it easy to introduce them, use them, and show their power.

**Comment by fmichonneau** [comment]
thanks for bringing this up @valkcano26 and thanks for the text suggestions @tkphd .
