### ISSUE TITLE
missing solution for scatterplot facet exercise

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#165]
Submitted via email. 

To complete my checkout for instructor training, I would like to describe a potential improvement to:
Open Refine for Ecology: Examining Numbers in OpenRefine: Scatterplot facet
My suggestion:

The exercise for the Scatterplot facet does not have a solution associated with it at the moment.
When I was completing the lesson, I didn't know what the answer to question 2 would be and I would have preferred to see the solution.

**Comment by ljvillanueva** [comment]
Dupe of #156. Closing.
