### ISSUE TITLE
Addressing data types within the OpenRefine lesson

### ISSUE THREAD

**Issue by hollyel** [datacarpentry/OpenRefine-ecology-lesson#166]
Going through the lessons I came across a few points at which data types are mentioned that might be confusing or come in at an odd point. The first mention of data types is in the very first exercise in Episode 2. For a learner to find the solution they have to figure out multiple features that were not previously mentioned or explained (e.g. what the current data type of a cell is, how to change the data type) within an exercise that is built to address initial understanding of faceting. A full explanation of data types and how data is interpreted at import into OpenRefine is not addressed until Episode 4, Examining Numbers. I would suggest:

- Adding text to the "Working with OpenRefine" section on creating a project to explain that on import all columns are treated as having a text/string data type rather than addressing this at the beginning of Episode 4. This information is important to understanding some of the capabilities of OpenRefine and for how data is interpreted upon import, as well as why OpenRefine is powerful tool for cleanup and not changing the raw data. 
- Remove the second part of the first exercise and include the information under the solution as a group activity during the explanation of facets or remove it and address this information later (similar concepts are already covered within Episode 4) 

A related note can be found under issue #72

**Comment by debpaul** [comment]
@hollyel this works for me. Thank you for adding your insights. I'll add this to our to-do list.

**Comment by villanueval** [comment]
Closing as implemented.
