### ISSUE TITLE
Typo mistake- instructor contribution checkout

### ISSUE THREAD

**Issue by kmutasa** [datacarpentry/OpenRefine-ecology-lesson#167]
**Lesson: Exporting and Saving Data from OpenRefine**
Solution: This project will include all the raw data and cleaning steps that were part of the _origina_ project.

the statement should be: This project will include all the raw data and cleaning steps that were part of the _original_project.

Regards 
Kudakwashe Mutasa

**Comment by debpaul** [comment]
Hello @cmacdonell - I fixed this typo directly in the file. Thanks @kmutasa for finding this. Closing this ticket now.
