### ISSUE TITLE
Minor correction to text (Episode 7)

### ISSUE THREAD

**Issue by mfernandes61** [datacarpentry/OpenRefine-ecology-lesson#171]
Resources for OpenRefine:
In second set of bullet points:-
"Grateful Data is a fun **sight** with many resources devoted to OpenRefine, including a nice tutorial."
should be
"Grateful Data is a fun **site** with many resources devoted to OpenRefine, including a nice tutorial."

**Comment by fmichonneau** [comment]
it looks like it has already been fixed. Thanks for the report @mfernandes61!
