### ISSUE TITLE
Broken links in Lesson 6 - resources

### ISSUE THREAD

**Issue by mfernandes61** [datacarpentry/OpenRefine-ecology-lesson#173]
The links below (from second section of references) are broken. They should either be fixed or removed/replaced with others.
----------
* Intersect Course Resources has Jared Berghold's Cleaning & Exploring your data with Open Refine (scroll down page to find).
* Enipedia OpenRefine Tutorial
-----------

HTH,
Mark

**Comment by fionajones** [comment]
Intersect Course Resources link brings back "You are not authorized to access this page" error so I think this link should be removed.
Enipedia OpenRefine Tutorial link worked for me.

**Comment by wanofii** [comment]
We have tried to search Jared Berghold's Cleaning & Exploring your data with Open Refine on Google. This page is no longer available. So, the link/page should be  removed . We have the "Enipedia OpenRefine Tutorial" and it effectively works.
I was submit the pull request to remove the broken link from the Resources page.
