### ISSUE TITLE
Merge OpenRefine Lessons - Ecology and Social Science

### ISSUE THREAD

**Issue by Librarianblues** [datacarpentry/OpenRefine-ecology-lesson#174]
I am attempting to complete my instructor training tasks and wanted to contribute to the OpenRefine lessons, but instead I am going to raise a higher level issue because I am baffled as to why the Carpentries are maintaining 2 different versions of the OpenRefine lesson? 

- Ecology curriculum http://datacarpentry.github.io/OpenRefine-ecology-lesson/
- Social Science curriculum http://www.datacarpentry.org/openrefine-socialsci/

OpenRefine is not limited, or specific to any discipline area, and the basics can be explained without reference to discipline specific data. So maintaining duplicate lessons seems odd.  Even if the audience of the lessons are different the basics remain the same. 

I recommend to the maintainers of Ecology and Social Science to consider merging the lessons, create a new lesson plan explaining all the major concepts already present in the 2 lessons (no need to add more) and to create/adapt exercises that will work for either sample of exercise data science/social science.  Instructors of the new workshop to then be told to include/not include sections as required to suit their audiences and time eg, regular expressions included in Soc Sci lesson but not Ecology.  

This maybe obvious but enacting the recommendation above will then create a single lesson which will make it easier to maintain, take less people to maintain, allow easier development because new instructors like myself will be able to create issues/pull requests in a central place rather than attempting to do it in two places.

A further recommendation is to have OpenRefine as a separate lesson listed on the Software-Carpentry site https://software-carpentry.org/lessons/. The advantage being that it will allow OpenRefine to appear in a single and prominent place for users instead of being hidden inside the Data Carpentry web site.

I am happy to contribute to the development, so let me know.

Cheers

Ryan

**Comment by debpaul** [comment]
Hello Ryan, I really appreciate your insights and take on these topics. I'm not sure though about implementing what you suggest. At the moment, several of us are in the process of customizing this lesson (and the entire Ecology lesson set) for natural history collections. As part of this process, we are changing out the dataset (as you suggest), but we will also be curating the skills covered - and so potentially adding / removing as seems best for the data manipulations most needed for this type of data. In essence too, it is the Carpentries philosophy that lessons are discipline-specific - to engage communities and manage cognitive load most effectively.

**Comment by debpaul** [comment]
These lessons are technically part of the Data Carpentry Curriculum, not the Software Carpentry Curriculum. I know of no plans (at the moment) to merge. I do see your "advantage" - you mean that those folks using the Software Carpentry pages miss this repo.
