### ISSUE TITLE
Episode 1 Introduction - aligning learning objectives and content

### ISSUE THREAD

**Issue by fionajones** [datacarpentry/OpenRefine-ecology-lesson#175]
Three of the current learning objectives do not align well with the content of the episode.
1. Describe OpenRefine's uses and applications: Although "capturing actions applied to raw data" and "data cleaning" are mentioned, there is no explicit, simple explanation of what you might want to use OpenRefine for.
2. Differentiate data cleaning and data organisation: There is no definition of data cleaning provided and I data organisation is not mentioned. These two concepts are not differentiated during the lesson.
3. Experiment with OpenRefine's user interface - there is no opportunity to work in OpenRefine in this episode.

There are also no challenges incorporated into the episode to check learner understanding.

Below find my suggestion for editing the lesson. It includes new learning objectives, new content, and an exercise.
---
Learning Objectives - Students will be able to:
1. Install OpenRefine on their machine.
2. Describe OpenRefine's uses and applications.
3. Locate helpful resources to learn more about OpenRefine.

Lesson
1. The following setup is necessary before we can get started (instructions here http://www.datacarpentry.org/OpenRefine-ecology-lesson/setup/).
Do you need help with any of the following?
(a) Google Chrome is set as your default browser (alternative is Mozilla Firefox)
(b) Download and install software from http://openrefine.org
(b) Download this data file https://ndownloader.figshare.com/files/7823341 and save to your desktop
2. What is OpenRefine?
(a) OpenRefine is a Java program that runs on your machine rather than in the cloud. Although it runs inside your browser, no web connection is needed. 
(b) OpenRefine does not modify your original dataset. All actions are easily reversed in OpenRefine and you can capture all the actions applied to your data and share this documentation with your publication as supplemental material.OpenRefine saves as you go. You can return to the project at any time to pick up where you left off, or export your data to a new file.
(c) OpenRefine can be used to standardise and clean data across your file. It can help you:
	(i) Get an overview of a data set
	(ii) Resolve inconsistencies in a data set
	(iii) Help you split data up into more granular parts
	(iv) Match local data up to other data sets
	(v) Enhance a data set with data from other sources
	(vi) Save a set of data cleaning steps to replay on multiple files
3. OpenRefine is a powerful, free and open source tool with a large growing community of practice. More help can be found at http://openrefine.org

Exercise
1. What inconsistencies might be in a data set? Can you think of any examples?
2. Can you think of a scenario in which you might want to split the data in the cells in a single column into separate columns?
---
Thanks for your consideration of my suggestion. Note that I have used some material from the Library Carpentry OpenRefine lesson, Episode 1 Introduction to OpenRefine https://librarycarpentry.github.io/lc-open-refine/01-introduction/

**Comment by fmichonneau** [comment]
thanks for your suggestions, we edited the content of the lesson to include your comments.
