### ISSUE TITLE
Introduction need additional information

### ISSUE THREAD

**Issue by bscheffler** [datacarpentry/OpenRefine-ecology-lesson#182]
I think a little more selling on the value of OpenRefine in the introduction might bring more people into participating in the Data Carpentry.  I think it would be helpful to indicate that this helps with version control of modifications, leads to reproducible data and easy to export to standard formats.

**Comment by deidrewhitmore** [comment]
+1 including a point about OpenRefine facilitating reproducible research. This could either be incorporated into the point about including the documentation as supplementary material alongside a publication or as its own point, which could include a statement about sharing among collaborators so they are aware of the alterations to the data.

**Comment by jellenf** [comment]
I think this is a great idea and I'm happy to work on this. Maybe an additional point in the introduction after the note about including documentation as supplementary material. It might be worth pointing out the transformation history can be exported as a JSON file?

**Comment by AbiReg** [comment]
I feel creating project as a lesson should be in the introduction instead of a stand alone lesson

**Comment by villanueval** [comment]
Closing as idea is implemented.
