### ISSUE TITLE
Expanding lesson to show how to use JSON script on datasets to enhance understanding of scripts

### ISSUE THREAD

**Issue by seduke** [datacarpentry/OpenRefine-ecology-lesson#183]
There is some technical jargon that is used which is not clearly explained for the novice user.  The concept of a script (JSON) and compressed files (tar.gz) are not assumed to be known by students in these workshops.  For instance, some of the problems students may have is unzipping a .zip file;  which is a fairly common form of compressed file.   So while it is said that the scripts can be applied to other datasets-- this would be something that would be useful to show how to apply the script to other datasets.  
Would it be possible to divide the data set used for this lesson and apply the script to a second dataset and then merge the two datasets into the one original.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by mamsikhantsi** [comment]
I am fairly a novice to use programming however i learned that OpenRefine cannot be easily accessible from certain browsers- especially when using windows operating system so i had to try out other browsers and it worked very well- All of the lessons up to thus far have not given me any problem, all i need to do is update as often as i can. 
Would it be possible to upgrade the lessons or the curriculum or even include new data sets altogether- the ones on the repository are very good however they have been there for a while now

**Comment by debpaul** [comment]
Hello Motlagomang Mamsi Khantsi, thanks for your feedback. Glad you 
managed to find a compatible browser. There are no plans at the moment 
to include new datasets.

But, there are others (Library Carpentry, Natural Science Collections) 
who have Open Refine lessons using different datasets. You can certainly 
write up a lesson and then share it with everyone.

There are some tentative plans to upgrade the lesson adding some more 
skills.


On 2018-08-15 11:20 AM, Motlagomang Mamsi Khantsi wrote:
>
> I am fairly a novice to use programming however i learned that 
> OpenRefine cannot be easily accessible from certain browsers- 
> especially when using windows operating system so i had to try out 
> other browsers and it worked very well- All of the lessons up to thus 
> far have not given me any problem, all i need to do is update as often 
> as i can.
> Would it be possible to upgrade the lessons or the curriculum or even 
> include new data sets altogether- the ones on the repository are very 
> good however they have been there for a while now
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datacarpentry_OpenRefine-2Decology-2Dlesson_issues_183-23issuecomment-2D413231051&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=9cj6K3HwXleAiUBn4Pyelaa-QtcNwXazR2sOJ0LzZnE&s=KHHzJ4nkCcPyIrOkWMqJMYqDapQHQjAlAOsmjjJaF94&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AC2gSx7hqpHBOoKi-2DGGYauzMHUScO22Wks5uRDxBgaJpZM4UuM1L&d=DwMFaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=ODXYRdWm1Oqf5-w5G2NjQw&m=9cj6K3HwXleAiUBn4Pyelaa-QtcNwXazR2sOJ0LzZnE&s=OpM-_70fMcFUmX9J9jVvNWzS8gaBMPmW8E2SRPnwgpk&e=>.
>

-- 
-- Upcoming iDigBio Events https://www.idigbio.org/calendar
-- Deborah Paul, iDigBio Digitization and Workforce Training Specialist
iDigBio -- Steering Committee Member
SPNHC Liaison, Member-At-Large and Member International Relations Committee
SYNTHESYS3 Representative
Institute for Digital Information, 234 LSB
Florida State University
Tallahassee, Florida 32306
850-644-6366

**Comment by debpaul** [comment]
We would welcome a pull request that addresses the wishes to elaborate on explanation of JSON and opening .zip files, as well as how to incorporate JSON script use into the lesson.

**Comment by seduke** [comment]
Debbie
I am new to this process and this suggestion was part of my trainer requirements.
What exactly is a pull request?
How do we move forward?
Thanks
Sara

**Comment by mamsikhantsi** [comment]
For Sara: i have not worked on zip files in OpenRefine, however i think its possible. But try on one file ata a time then you merge the files, OpenRefine "cleans up"data, filter and sorting- then you can cluster it-The way to contribute to the lessons is to fork the repository update the lesson and make a pull request. You can read more on the process here:
https://guides.github.com/activities/hello-world/

**Comment by villanueval** [comment]
Closing as idea is implemented by explaining how to apply. Further details about JSON and tar.gz files may be outside the scope.
