### ISSUE TITLE
Minor corrections to Lesson 01 - Working with OpenRefine

### ISSUE THREAD

**Issue by abigailsparling** [datacarpentry/OpenRefine-ecology-lesson#186]
A few minor corrections for Lesson 01 - Working with OpenRefine:

Following **Creating a Project** capitalize click in step one - "1. [C]lick Create Project and select Get data from This Computer."

Following **More on Facets** add Open to Refine - "As well as ‘Text facets’ [Open]Refine also supports a range of other types of facet."

Following **Split** correct the spelling of columns in step one - "1. Let us suppose we want to split the scientificName column into separate colum[n]s for genus and for species."

**Comment by debpaul** [comment]
Thanks @abigailsparling for taking the time to read through so carefully to find these. They are all fixed now. Closing this ticket.
