### ISSUE TITLE
Extra Exercise for Open Refine lesson

### ISSUE THREAD

**Issue by tadamus** [datacarpentry/OpenRefine-ecology-lesson#205]
I have been teaching Data Carpentry for a few years and I have always felt the Open Refine lesson was too short, including demos without a lot of opportunity for learners to try the things. I wrote this cheat sheet of the paths needed during the lesson because I have found that the drop downs can sometimes confuse people, especially if they fall behind. Also I am including a link to a data set, and questions that I created to help learners implement what they have learned about Open Refine.  The data set contains metadata on 311 calls in New York City during Hurricane Sandy and can be found here: [https://data.cityofnewyork.us/Social-Services/sandyrelated/fs5z-tpv4]. I have taught this as part of the Ecology lesson, as that is what we teach at the University of Wisconsin - Madison, but since it is social science data it may be better suited for the social science data carpentry lesson.
[OpenRefineSheet (1).docx](https://github.com/datacarpentry/OpenRefine-ecology-lesson/files/2577997/OpenRefineSheet.1.docx)

**Comment by debpaul** [comment]
Hi Trisha,

Yes, you are correct! This lesson was originally written as a DEMO taking about 20-30 minutes max. It does indeed need adding to, but the time allotted for it will need to vary then, according to what will be covered. Thanks very much for sharing your lesson enhancement.

**Comment by villanueval** [comment]
Closing as lesson is not so short anymore.
