### ISSUE TITLE
Suggestions for Intro to Open Refine History

### ISSUE THREAD

**Issue by IngridReiche** [datacarpentry/OpenRefine-ecology-lesson#207]
**Below in Bold is one correction and two small pieces of additional background on OpenRefine**

A part of the data workflow is preparing the data for analysis. Some of this
involves data cleaning, where errors in the data are **identified** and corrected 
or formatting
made consistent. This step must be taken with the same care and attention
to reproducibility as the analysis.

OpenRefine (formerly Google Refine, **and originally known as Freebase Gridworks developed by Metaweb in 2010**) is a powerful free and open source tool 
for working with messy 
data: cleaning it and transforming it from one format into another.

This lesson will teach you to use OpenRefine to effectively clean and format
data and automatically track any changes that you make. Many people comment
that this tool saves them literally months of work trying to make these
edits by hand.

.....

> #### Prerequisites
>
> This lesson requires a working copy of OpenRefine (previously called 
> GoogleRefine, **and originally known as Freebase Gridworks**).    
> <br>To most effectively use these materials, please make sure to install 
> everything *before* working through this lesson.
{: .prereq}

**Comment by debpaul** [comment]
Thanks @biblioFile for your contribution to add the original developers 
of this magical tool.

**Comment by Bibliofile** [comment]
Huh? I think you might have tagged the wrong person.

**Comment by ljvillanueva** [comment]
Closing this issue and leaving any discussion in the pull request #210

**Comment by ljvillanueva** [comment]
Closing since the information is too old and is no longer relevant for the use of the tool. 

Feel free to reopen/comment if anyone thinks this should be kept.
