### ISSUE TITLE
Cluster and edit button

### ISSUE THREAD

**Issue by jifar** [datacarpentry/OpenRefine-ecology-lesson#212]
In the lesson on Open Refine-ecology there is a reference to the 'Cluster' button in point 1. of the Clustering section. There is an alternative method for editing the cells under 'Edit cells' > 'Cluster and edit...' which works as well as the method used in the example (Text Facet then 'Cluster'). I'd like to request that the second method be included parenthetically. I missed the suggested method because I went exploring while I went through the lesson.

Also, there is a sentence under Faceting which could be reworked from "A 'Facet' groups all the like values that appear in a column, and then allow you to filter the data by these values and edit values across many records at the same time." I would like to suggest the following wording:

"A 'Facet' groups all the like values that appear in a column, and allows you to filter the data by those values. It also allows you to edit values across many records at the same time."
  
---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by villanueval** [comment]
PR based on the issue was merged. Closing.
