### ISSUE TITLE
CONTRIBUTING.md instructions- why is installing git required?

### ISSUE THREAD

**Issue by jhammock** [datacarpentry/OpenRefine-ecology-lesson#218]
This issue is not specific to this lesson; it's about the CONTRIBUTING.md file which appears in each lesson repository and appears to be separately maintained in each. (I am a child in these matters, but I gather this happens, as sharing things among repositories is... complicated.)

I notice that the CONTRIBUTING.md files section on contributing via github assumes the contributor has git installed. I would expect many data carpentry students and trainers-in-training to be more comfortable forking a lesson file within github.

NB: I am in the process of checking out of instructor training, but am not sure this is an eligible contribution. Please don't worry about it. I will proceed back to the lesson text and attempt a regular contribution shortly.

**Comment by ljvillanueva** [comment]
Maybe this was related to an older version of the file. The CONTRIBUTING.md file now lists other ways to contribute that do not require git. 

Closing issue.
