### ISSUE TITLE
Add instructions to remove sort after first sorting exercise 

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#224]
(Received by email from Instructor trainee)

My suggestion is to add the text "Before moving on to the next exercise, remove the Month sort" where the asterisk is on the screenshot.

Reason for change: The next exercise asks the students to sort by plot. If the Month sort is not first removed, the Plot sort is added to the Month sort and (1) it makes the answer difficult to find and (2) it would have the students sort by multiple columns before it is introduced in the lesson plan.

**Comment by ErinBecker** [comment]
(submitted by email) For Issue #224, "Add instructions to remove sort after first sorting exercise" in the OpenRefine lesson for the Ecology Data Carpentry curriculum, I think a good amendment would be to add "Be sure to remove the Month sort before adding the Plot sort" to the Solution box so that students aren't necessarily given that right away and would encourage more thinking.

**Comment by villanueval** [comment]
Closing as implemented in solution.
