### ISSUE TITLE
Scatterplot Facet not working correctly

### ISSUE THREAD

**Issue by gjblyth** [datacarpentry/OpenRefine-ecology-lesson#226]
I am new to Carpentries and it may be that this issue is already widely known and this may not be the best place to raise this.

It appears there is a known issue with Scatterplot Facet graph generation
OpenRefine Pull requests #2117 #2140

It is likely that this does not occur on all platforms or configurations. For me the problem has appeared on Windows 7 and Windows 10 computers, using Chrome and Firefox and with the Ecology and Social Science datasets - all with version 3.2 of OpenRefine.

At least an additional bullet to the Common Problems section of the Instructor Notes might be a good idea.

![image](https://user-images.githubusercontent.com/29864605/66124760-2e5eab00-e5dd-11e9-894f-a9cb747d0081.png)

**Comment by atraxler** [comment]
I ran into this issue, and for me it was fixed by the 3.3 beta release (change notes [here](https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.3)). Not sure if the lessons are allowed to use beta versions, or need to stick to the latest full release.

**Comment by gjblyth** [comment]
Thanks Adrienne, good to know that a fix is on the way even if only in beta at this stage. I would consider running a class with the full release and doing a demo with the beta. Though I am very much a newcomer to carpentries.

**Comment by ljvillanueva** [comment]
Seems this issue was solved in the OpenRefine code in https://github.com/OpenRefine/OpenRefine/pull/2140. 

Closing.
