### ISSUE TITLE
Browsers used by participants - Localhost vs 127.0.0.1

### ISSUE THREAD

**Issue by zjsteyn** [datacarpentry/OpenRefine-ecology-lesson#23]
In a recent workshop some time was spent struggling to get OpenRefine started on participants' laptops with one unique error coming up which relates to **00-getting-started.html** and spesifically: 

> If you are using a different browser, or OpenRefine does not automatically open for you, point your browser at http://127.0.0.1:3333/ to launch the program.

Possible issues with the host file on Windows caused that OpenRefine could only open using localhost instead of 127.0.0.1. The instructor came across the solutions, but only after some time. It may be useful to add the the following text "at http://127.0.0.1:3333/ **or http://localhost:3333**" to the instructor notes & lesson itself it may save some time for the instructor and participants.

**Comment by debpaul** [comment]
Thanks @zjsteyn very helpful! I'll be making this change in just a minute.
