### ISSUE TITLE
English language wording in one of the lessons

### ISSUE THREAD

**Issue by aasiyahrashan** [datacarpentry/OpenRefine-ecology-lesson#231]
Hi, 

The getting started section of this lesson uses the word `insure`. I think it may be more appropriate to use the word `ensure` in this context. 

![Screen Shot 2019-11-01 at 15 07 01](https://user-images.githubusercontent.com/9165437/68034535-bbb71d00-fcb9-11e9-92dd-5eacd134190c.png)

Thanks|

**Comment by JenDaub** [comment]
I agree on this one, pretty confident it is 'ensure' not 'insure'. I need to do a carpentries check out so was going to go ahead and make a PR to fix this?

**Comment by JenDaub** [comment]
This error is on the following page: https://datacarpentry.org/OpenRefine-ecology-lesson/
I am confident this should be "ensure" not "insure" so will go ahead and make an PR edit for this as I need to do a carpentries instructor check out.

**Comment by pdoehle** [comment]
@rachellombardi Looks like we can merge #240 and close this once that's done.
