### ISSUE TITLE
Change recommendation about setting a default browser

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/OpenRefine-ecology-lesson#233]
I would suggest changing the recommendation about setting default browser to Chrome or Firefox.  There may be other reasons why an individual has default browser settings configured and and I would not want this to impact other work that they do.  Instead, we can as them to open  http://127.0.0.1:3333/ or http://localhost:3333  in Chrome or Firefox.

**Comment by pdoehle** [comment]
Great point @maneesha. Thanks for the pull request @arieldeardorff. I've merged this pull request and will close this issue.
