### ISSUE TITLE
Note what kind of URLs data can be uploaded from

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/OpenRefine-ecology-lesson#236]
The lesson notes that: 

> Note that at step 1, you could upload data in a standard form from a web address by selecting Get data from Web Addresses (URLs). However, this won’t work for all URLs.

I would recommend some information on what types of URLs this will or won't work from.

**Comment by ljvillanueva** [comment]
Related to #64.

**Comment by villanueval** [comment]
Thanks for the suggestion. The [documentation](https://docs.openrefine.org/manual/starting#web-addresses-urls) mentions this option but doesn't explain more details, it will be very specific cases where it might not work. This feels like too much detail or advanced use for an introduction to OpenRefine, so I'm closing it.
