### ISSUE TITLE
Consistent capitalization of Facet/facet

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/OpenRefine-ecology-lesson#237]
The word "facet" is inconsistently capitalized throughout the OpenRefine lessons.  I don't use this enough to know if there a standard but I would suggest keeping consistent with this.

**Comment by ljvillanueva** [comment]
The manual uses `facet`, so it should be in lowercase across the lessons.

**Comment by villanueval** [comment]
Fixed with #264
