### ISSUE TITLE
Writing Transformations

### ISSUE THREAD

**Issue by mksalmon** [datacarpentry/OpenRefine-ecology-lesson#241]
In my opinion adding a section introducing and writing transformations would be a good addition to the Data Cleaning with OpenRefine for Ecologists.  This section would introduce GREL and would describe how to write a valid GREL expressions.  Google Refine Expression Language (GREL) is  a powerful tool in data cleaning using OpenRefine and would be a good addition to this lesson.  The writing transformations is included in the OpenRefine workshop in Library Carpentry.

**Comment by ljvillanueva** [comment]
Link to Library Carpentry lesson: https://librarycarpentry.org/lc-open-refine/07-introduction-to-transformations/index.html

https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/_episodes/07-introduction-to-transformations.md

**Comment by villanueval** [comment]
The lesson now has a step for applying GREL expressions. Will need to expand a bit to explain them better.
