### ISSUE TITLE
Examining Numbers in OpenRefine - Numeric facet

### ISSUE THREAD

**Issue by MargoLawrence** [datacarpentry/OpenRefine-ecology-lesson#249]
I can't see these appearing in the facet box - I can only see a blue square with numbers 0 - 36,000 for recordID.

3. Notice that there are several checkboxes in this facet: Numeric, Non-numeric, Blank, and Error. Below these are counts of the number of cells in each category. You should see checks for Non-numeric and Blank if you changed some values.

![image](https://user-images.githubusercontent.com/30249858/96067985-60486400-0ef7-11eb-943a-6f24dcd2759c.png)

**Comment by rachellombardi** [comment]
Hi @MargoLawrence, 
Thank you for bringing this to our attention! 

I was able to reproduce your screenshot if I skipped step 1 ("For a column you transformed to numbers, **edit one or two cells, replacing the numbers with text (such as abc) or blank (no number or text)**." 

Can you please redo this exercise, being sure to change some of the cells to have non-numeric values, and let us know if you receive the same or different outcome?

Thank you!

**Comment by MargoLawrence** [comment]
Hi

I cannot get into OpenRefine again – I run the .exe successfully and then go to the links – but neither work

http://127.0.0.1:3333/ or http://localhost:3333/

The error messages say:

This site can’t be reached
127.0.0.1 refused to connect.
localhost refused to connect.

How do I open it again?

Ngā mihi nui,

Margo Lawrence

Senior Applications Support Analyst
06 951 8036 - x85036


http://askus.massey.ac.nz<http://askus.massey.ac.nz/>

**Comment by rachellombardi** [comment]
Hi @MargoLawrence, 

What version of OpenRefine are you using? If you are still having issues, I would try uninstalling OpenRefine and then re-installing the latest version. 

Please let me know if that works!

**Comment by rachellombardi** [comment]
Hi @MargoLawrence, 

Since we still haven't heard back whether you were successful at running OpenRefine, I am going to close this issue. If you are still unable to use OpenRefine, please create a new one and we will be happy to help you continue troubleshooting. 

Best, 
Rachel
