### ISSUE TITLE
Various lesson improvements in a separate repo

### ISSUE THREAD

**Issue by anenadic** [datacarpentry/OpenRefine-ecology-lesson#251]
We did a copy (rather than a fork) of this lesson at: https://github.com/Southampton-RSG/openrefine-data-cleaning. The main modifications include:

- a lot of the screenshots were added to help make this lesson suitable for self-learning and making it easier for learners to follow it on their own (this will help new instructors (who are not familiar with the OpenRefine interface) get up to speed faster)
- removed some of the repetitive text and tightened the narrative a bit

I'd like to invite you to have a look and review this version of the lesson. If you feel that this is something worth merging back into the main lesson, I'd be happy to with you to make a fork that would be suitable for creating a PR.

**Comment by anenadic** [comment]
Tagging @pdoehle as not sure who the current official maintainers of the lesson are.

**Comment by pdoehle** [comment]
@anenadic , thanks for the heads up. I'm excited to look through what you have done. I will get together with @rachellombardi and have a look.

**Comment by ljvillanueva** [comment]
@anenadic I'm looking into old issues and PR of this repo. 

Do you mind taking a look at the changes you made and submitting them as pull requests? Some are outdated, but I'd like to see your contributions make their way into the repo. Thanks!

**Comment by anenadic** [comment]
Hi @villanueval @rachellombardi,

It's been a while but hope it is not too late to continue this thread - I have moved all the changes now to a different repo: https://github.com/softwaresaved/data-cleaning-openrefine which is nicely synched up with the lates changes in this repo. See the new PR: https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/273.

**Comment by villanueval** [comment]
Hi @anenadic, thank for this! I'll take a look in the next couple of weeks and incorporate your contributions.

**Comment by villanueval** [comment]
Closing as implemented many of the suggested changes.
