### ISSUE TITLE
Link redirect in Introduction Basics of OpenRefine

### ISSUE THREAD

**Issue by ckearney07** [datacarpentry/OpenRefine-ecology-lesson#253]
It looks like there's a redirect link for GREL under [Basics of OpenRefine.](https://datacarpentry.org/OpenRefine-ecology-lesson/00-getting-started/index.html). If you'd like to update it, the new link is now https://docs.openrefine.org/manual/grelfunctions/

**Comment by evanwill** [comment]
I opened PR  #254 to update all the old wiki links to the new User Manual. The Wiki documentation is being phased out, so it should be updated.

**Comment by ljvillanueva** [comment]
Thanks! Updated links merged to repo.
