### ISSUE TITLE
clarification of filtering instructions

### ISSUE THREAD

**Issue by karenword** [datacarpentry/OpenRefine-ecology-lesson#265]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

I propose some clarification under filtering #2 a I recommend a change from

Type in bai and press return. There are 48 matching rows of the original 35549 rows (and these rows are selected for the subsequent steps).

to

Type in bai and press return. There are 48 matching rows of the original 35549 rows (and these rows are selected for the subsequent steps). _Only a subset of the 48 rows appear._

**Comment by villanueval** [comment]
Added in #267
