### ISSUE TITLE
Word edit suggestion in "Working with OpenRefine"

### ISSUE THREAD

**Issue by sc3tulok** [datacarpentry/OpenRefine-ecology-lesson#272]
https://datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/index.html 

In the lesson "Working with OpenRefine" the 2 objectives below are listed. 

- Recall what facets are and how they are used to sort and summarize data.
- Recall what clustering is and how it is applied to group and edit typos.

The word _recall_ may seem confusing to some students (that are not ecologists) using this lesson to learn OpenRefine. Facets and clustering are not mentioned before this lesson. Keeping in mind that "These lessons assume no prior knowledge of the skills or tools", would the following wording be more clear for all students?

- Use facets to sort and summarize data.
- Use clustering to group and edit typos.

Thank you for your consideration.

**Comment by villanueval** [comment]
Thanks for the suggestion!

The text has been replaced and re-organized, so closing issue.
