### ISSUE TITLE
Missing episode: Reconciliation of Names

### ISSUE THREAD

**Issue by chillenzer** [datacarpentry/OpenRefine-ecology-lesson#277]
Hi,
I just found that [Reconciliation of Names](https://github.com/datacarpentry/OpenRefine-ecology-lesson/blob/gh-pages/_episodes/05-reconciliation.md) only contains the beginning of [Transforming Data](https://github.com/datacarpentry/OpenRefine-ecology-lesson/blob/gh-pages/_episodes/03-transforming-data.md). I guess that this is not the desired episode content, right?
Best,
Julian

**Comment by villanueval** [comment]
Thanks for catching this! It was an early deployment of the big changes coming to the lesson. I've removed that episode, which eliminates the duplicate contents.
