### ISSUE TITLE
OpenRefine & loopback adapter in Win10

### ISSUE THREAD

**Issue by mikewallis** [datacarpentry/OpenRefine-ecology-lesson#29]
If the loopback adapter isn't installed in the Windows instance - for example, on a new laptop - then 127.0.0.1 isn't routeable by the web browser and OpenRefine will look like it's starting up, but won't connect as 127.0.0.1 is hard-coded into all the connectivity bits. 

It's fixable by installing the loopback adapter (https://technet.microsoft.com/en-gb/library/cc708322(v=ws.10).aspx) or by changing 127.0.0.1 to "localhost" in the address bar, but this can cause problems when uploading data from the client to the OpenRefine server. 

This caused quite a bit of confusion in a workshop where a participant had a Win10 laptop and I spent a little while trying to work out why I couldn't even ping 127.0.0.1 from the command line.

**Comment by debpaul** [comment]
Thanks @mikewallis I note there is already a reference in the documentation to try "localhost". But you are saying that this too can cause data upload problems? Best course of action seems to be that we add your fix in the list of options. I myself have a Win10 machine - and have been running Open Refine in Firefox with no problems. Do you know what web browser this person was using? (Chrome?)

**Comment by debpaul** [comment]
I also note this Loopback adaptor requires Admin privileges on one's computer. We often have participants that do not have this level of permissions. So, they'd need to take care of this install - and validate it runs, before the workshop.

**Comment by Nasidiqi** [comment]
how do i re start Open refine? i ahve been not able to reuse it after restarting my PC?

**Comment by debpaul** [comment]
Hi Nasidiqi,
I do not know. Maybe someone else here will know. You could always try uninstalling it and reinstalling.

It would be helpful if you tell us what platform (Mac or Win or Unix) and what browser you use.

Sent from Shoe (my iPhone)

On Feb 8, 2019, at 10:10 PM, Nasidiqi <notifications@github.com<mailto:notifications@github.com>> wrote:


how do i re start Open refine? i ahve been not able to reuse it after restarting my PC?

**Comment by Nasidiqi** [comment]
Hi, 

I am using Windown 10 and using chrome. I installed it and then restared my computer since then i am not able to access it?

Also it does not load complete excel file. my file has about 20,000 rows and it loads only 3345 rows And its rows not records.

**Comment by ljvillanueva** [comment]
Old issue related to a very particular windows issue. Not answered if localhost was enough. Seems to be a Windows issue where a computer might get some settings messed up, not related to the lesson. 

Closing issue.
