### ISSUE TITLE
URLs seem incorrect in setup.md for OpenRefine 

### ISSUE THREAD

**Issue by debpaul** [datacarpentry/OpenRefine-ecology-lesson#292]
- What do I want to do? From here https://datacarpentry.org/OpenRefine-ecology-lesson/
I'd like to get the specific link to the `Software` section to share, for example in an email.

**Question:** How are you generating these links to sections of the markdown page? In looking at them I see links like this
- https://datacarpentry.org/OpenRefine-ecology-lesson/#about-the-data which is what I would expect.

**Issue**: then I see some links to different sections of the page that have the same URL, like this
Section URL
Data                     https://datacarpentry.org/OpenRefine-ecology-lesson/#prereq1
Software              https://datacarpentry.org/OpenRefine-ecology-lesson/#prereq2
For Instructors     https://datacarpentry.org/OpenRefine-ecology-lesson/#prereq2
Getting Started    https://datacarpentry.org/OpenRefine-ecology-lesson/#prereq1

I would expect to see 

Data                     https://datacarpentry.org/OpenRefine-ecology-lesson/#data
Software              https://datacarpentry.org/OpenRefine-ecology-lesson/#software
For Instructors     https://datacarpentry.org/OpenRefine-ecology-lesson/#for-instructors
Getting Started    https://datacarpentry.org/OpenRefine-ecology-lesson/#getting-started

Am I missing something? I find it odd that different sections of the page have the same URL+anchortag 
Thanks for help.

**Comment by bencomp** [comment]
That is a good observation, @debpaul. It appears this may be a bug. I will add an issue to the Workbench.

**Comment by bencomp** [comment]
[The Workbench](https://carpentries.github.io/sandpaper-docs/index.html) consists of several repositories; I think it should go in <https://github.com/carpentries/sandpaper/issues>. I see the same issue happen in [the lesson on OpenRefine for Social Sciences](https://datacarpentry.org/openrefine-socialsci/index.html), so this is related to the infrastructure, not this lesson.

**Comment by debpaul** [comment]
> [The Workbench](https://carpentries.github.io/sandpaper-docs/index.html) consists of several repositories; I think it should go in https://github.com/carpentries/sandpaper/issues. I see the same issue happen in [the lesson on OpenRefine for Social Sciences](https://datacarpentry.org/openrefine-socialsci/index.html), so this is related to the infrastructure, not this lesson.

Yes, that's what I wondered, they looked auto-generated. Thanks for pointing me to where they are, in case I note something else.

**Comment by bencomp** [comment]
I opened https://github.com/carpentries/sandpaper/issues/454 for this.

**Comment by bencomp** [comment]
This has been fixed thanks to carpentries/sandpaper#467.
