### ISSUE TITLE
Add module on using scatterplot facet for checking data quality

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#4]
One idea that came up with @debpaul and @seltmann is to add a module on how to use the Facet Scatterplot functionality to check for things like data outliers or to be able to zoom in on particular aspects of the data through the visualization. This could be some nice functionality for users.

**Comment by ljvillanueva** [comment]
Seem the proposed idea was added and the issue left open. Closing.
