### ISSUE TITLE
Readme.md got its content overwritten by a blank version of the readme template

### ISSUE THREAD

**Issue by dlstrong** [datacarpentry/OpenRefine-ecology-lesson#40]
In https://github.com/dlstrong/OpenRefine-ecology-lesson/commits/gh-pages/README.md 's comment history, there's a discussion about whether to convert .md endings to .html endings. 

At some point, though, someone did a revert that took a page with about 111 lines of content and replaced it with one that's the blank starter template. (I don't yet know enough Git to figure out exactly what happened, but the history has got a lot more stuff in it than what's showing in the readme right now.)

Here's what the readme shows right now: 

![image](https://cloud.githubusercontent.com/assets/3987376/21432372/dd5d732a-c830-11e6-8b32-7b42b6e47aa0.png)

It looks like that needs a different type of reverting to get the content back?

**Comment by ErinBecker** [comment]
Closed with #47
