### ISSUE TITLE
Check that 'OpenRefine' is used consistently in the lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#45]
In different places in the lesson, OpenRefine is sometimes 'Refine' or 'Open Refine'. Check for consistency and use 'OpenRefine' as in [http://openrefine.org](http://openrefine.org)

Inconsistency pointed about by @nickynicolson
https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/9

**Comment by ErinBecker** [comment]
Closed with #97
