### ISSUE TITLE
add content to services lesson 

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#46]
The services lesson 04-services.md needs content. @nickynicolson put in a nice PR https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/9 but noted that with our current data, it requires us to use a Google Maps API, which requires registration. GBIF would be an option that doesn't require a registration, but we would need to update the data. 

This issue is for after the current planned lesson release, and we would need to update the data as well as the services lesson.

**Comment by tracykteal** [comment]
I took the services lesson out for now, since it needed more information to be teachable, but we should plan on adding it back.

**Comment by Repositorian** [comment]
For the Data Carpentry Ecology workshop at Caltech starting today, I've added in a services component where we reconcile the Scientific Names against one or more authority files.  OpenRefine 2.7 release ships with Wikidata built into the reconciliation tab and it is pretty straightforward to add additional (presumably more authoritative) taxonomic sources such as NCBI taxonomy; UBio; GBIF; and Global Names index.  The WikiData service actually does work for some names and it provides an opportunity to explain open linked data a bit more.  This "bonus" piece will take place in a couple of hours for 30 Caltech grad students so let's see how it goes!

**Comment by ErinBecker** [comment]
@Repositorian - that sounds like a great addition. I'm excited to hear how it works out. 

For now, should we move the services module info into discussion with the plan to move it back out into it's own module after lesson release? This is similar to what we did for the "dealing with commas in data" module in Spreadsheets. What do y'all think?

**Comment by Repositorian** [comment]
The Services lesson worked well this morning at Caltech DataCarpentry.  Grad students from physics, chemistry and bio were enthusiastic to apply to their research! What we did was copy the scientific name column, rename it to Common name, and then pull the common names from Wikidata to populate that column.  I also was able to add additional taxonomic services to the Services list and demonstrate them, including GBIF, Global Names Index, NCBI taxonomy.  In these three cases, I was not adding a common name to a new column but validating the scientific names against those authority lists.  Does this component sound worthwhile?  If so, TeamCaltech can create a lesson for your review and feedback. What do you think?

**Comment by debpaul** [comment]
Sounds great Gail. +1

**Comment by villanueval** [comment]
Closing old discussion.
