### ISSUE TITLE
404 Page Not found -Scripts for OpenRefine

### ISSUE THREAD

**Issue by smeloro** [datacarpentry/OpenRefine-ecology-lesson#48]
At the bottom of the "Working with OpenRefine" page the next page for "Scripts for OpenRefine" returns a "404 Page not found" below is the link:

http://www.datacarpentry.org/OpenRefine-ecology-lesson/02-scripts.html

**Comment by debpaul** [comment]
Just time for a very quick look. Seems like the link needs to be changed to http://www.datacarpentry.org/OpenRefine-ecology-lesson/02-filter-exclude-sort.html Thanks for catching this @smeloro 

@tracykteal can you look at this - not sure why (can't remember) the link is different.

**Comment by ErinBecker** [comment]
Thanks @smeloro and @debpaul 

I took the prev/next links out because they're included in the new template, so this should be resolved now! See #101.
