### ISSUE TITLE
Not currently enough content for time allocated

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#5]
There is currently not enough content in this lesson for the time allocated. Addressing https://github.com/datacarpentry/OpenRefine-ecology/issues/4 might help.

This is something important to consider. We either need to add new content or adjust the time allocated.

**Comment by r-bowman** [comment]
A possible method to address this issue for the 01-working-with-openrefine lesson might be to add information about the methods and functions in Clustering to help attendees better understand the various options. This way they will understand what might work for them as they go back and use OpenRefine in their work.

**Comment by ErinBecker** [comment]
I think there is now ~1.5-2 hrs worth of content. 

https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/94
