### ISSUE TITLE
Data location

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#56]
Ideally the data for this workshop would be included in the Portal teaching database or somewhere other than Dropbox.

**Comment by ethanwhite** [comment]
This data is now available from the core figshare repo: https://ndownloader.figshare.com/files/7823341

**Comment by ErinBecker** [comment]
Thanks @ethanwhite - is this the same version of the data that is used in the exercises? I know that the data for the exercises was modified from the original (real) data to introduce the types of errors we want to talk about in the lessons. Can you confirm that the link above is the data used in the exercises?

**Comment by ErinBecker** [comment]
Closed with #100
