### ISSUE TITLE
Could use more background/motivation in 00-getting started

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#59]
There could be some more information about what data cleaning is and why it's important and how OpenRefine can help in the 00-getting-started lesson.

Some good ideas could come from

http://programminghistorian.org/lessons/cleaning-data-with-openrefine
http://thomaspadilla.org/dataprep/

**Comment by ljvillanueva** [comment]
Not clear if this was used for enhancing the lesson, but I'm closing it due to the age and that the use of OprenRefine is well described in the lesson.
