### ISSUE TITLE
Some rephrasing in 01-working-with

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#62]
"In this first step, we’ll browse our computer " could be rephrased. I think the intent here is to look at the file and what it looks like, before opening it in OpenRefine. 

Not sure if this is necessary, but it is good to describe the additional columns that were added

**Comment by ljvillanueva** [comment]
Not clear what the path to take to rephrase the text and linked pull is unrelated. Closing.
