### ISSUE TITLE
Take out section of 01-working-with

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#63]
Can remove:

"
[This part should probably be in 03-scripts.md file with follow-up: When doing this demo, the columns: JSON, decimalLatitude, decimalLongitude can be deleted, and then recreated if time, with a call to a locality service, and subsequent parsing of the JSON data returned by the service.]
"

**Comment by ErinBecker** [comment]
Addresses https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/93/files#diff-58b5fab52083ef6ed69d49fea2066398
