### ISSUE TITLE
More description of what faceting is

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/OpenRefine-ecology-lesson#65]
There's a good description of how to do faceting in 01-working-with, but there could be more of a description of what faceting is conceptually as an introduction.

**Comment by tkphd** [comment]
Addressed by #169, which adds the number of available styles in online shopping interfaces as a motivating example of faceting.

**Comment by ljvillanueva** [comment]
Linked issue/pull is not found. Seems faceting was better explained and issue left open.

Closing.
