### ISSUE TITLE
Install check for OpenRefine on Windows

### ISSUE THREAD

**Issue by Repositorian** [datacarpentry/OpenRefine-ecology-lesson#69]
Windows

- [_OK_] Check that you have Firefox or Chrome browsers installed and set as your default browser. OpenRefine runs in your default browser. It will not run correctly in Internet Explorer.
-  [_More explanation needed_]   Download software from http://openrefine.org
--It is not clear which release of OpenRefine you want the participant to download.  There are now *5* releases of OpenRefine available for download under the "Offcial Distribution' page! 
-  [_OK_] Unzip the downloaded file into a directory by right-clicking and selecting “Extract…”. Name that directory something like OpenRefine.
- [_OK_]  Go to your newly created OpenRefine directory.
- [_Need to concatenate this bullet with next one_]    Launch OpenRefine; ......
-  [_Error in file name and incomplete instruction: Suggested rewrite follows_]   Click the openrefine.exe (this will launch a command prompt window first, but you can ignore that and wait for OpenRefine to launch in the web browser, which is where you will interact with the program)
-  [-OK-] If you are using a different browser, or OpenRefine does not automatically open for you, point your browser at http://127.0.0.1:3333/ or http://localhost:3333 to launch the program.

**Comment by fmichonneau** [comment]
fixed by 5b07f72e1c71dda25a6ed8b8f8d93869fa66d185
