### ISSUE TITLE
Provide 'Additional resources'

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/OpenRefine-ecology-lesson#7]
Add a section 'Additional resources' or 'References'
Eg. ODI material:
http://training.theodi.org/InPractice/Day_1/ 
http://training.theodi.org/InPractice/Day_3/

**Comment by ErinBecker** [comment]
Now included as https://github.com/datacarpentry/OpenRefine-ecology-lesson/blob/gh-pages/_episodes/06-resources.md
