### ISSUE TITLE
Are Dropbox links sustainable?

### ISSUE THREAD

**Issue by cmacdonell** [datacarpentry/OpenRefine-ecology-lesson#70]
The rodent data comes from Dropbox. Dropbox links are changing https://www.dropbox.com/help/16

Check that this [link](https://www.dropbox.com/s/kbb4k00eanm19lg/Portal_rodents_19772002_scinameUUIDs.csv) will work for the foreseeable future OR consider moving data into the repo. The file is 5MB.

This question is worth asking of any external links.

**Comment by tracykteal** [comment]
I don't think any of the files we ask to be downloaded should be in Dropbox. They should be in something more universal and archivable. Most of the files for the Ecology lessons are in the [Portal Teaching Database on Figshare](https://figshare.com/articles/Portal_Project_Teaching_Database/1314459). We should add any additional ones there.

**Comment by tracykteal** [comment]
@ethanwhite would it be possible to add this file: https://www.dropbox.com/s/kbb4k00eanm19lg/Portal_rodents_19772002_scinameUUIDs.csv

that's used in the OpenRefine Ecology lesson, to the Portal Teaching Database in Figshare?

**Comment by cmacdonell** [comment]
There's a bit of Dropbox-specific text in 01-working-with-openrefine that will need to be adjusted when we move away from Dropbox.

`Note that at step 1, you could upload data in a standard form from a web address by using “Get data from” “Web Addresses (URLs)”. However, this will not work on a dropbox address as above.`

**Comment by cmacdonell** [comment]
Just noticed this is a duplicate of #56

**Comment by ethanwhite** [comment]
Done: https://ndownloader.figshare.com/files/7823341

**Comment by ErinBecker** [comment]
Closed with #100
