### ISSUE TITLE
First exercise of 01-working-with-openrefine has a unexplained concept

### ISSUE THREAD

**Issue by cmacdonell** [datacarpentry/OpenRefine-ecology-lesson#72]
The second task in the first exercise

`Is the column formatted as Number, Date, or Text? How does chaning the format change the faceting display?`

This task introduces the concept of the format of a column without explaining it. Also, the user has not previous been show how to change the format.

**Comment by Repositorian** [comment]
I agree with this point and might suggest that the YEAR column be used to demo this.  If we ask them to use the common transforms to change the column values to date format, they can then facet by date and even timeline.

**Comment by villanueval** [comment]
Closing as stale issue.
