### ISSUE TITLE
Typo and formatting in 02-filter-exclude-sort

### ISSUE THREAD

**Issue by cmacdonell** [datacarpentry/OpenRefine-ecology-lesson#74]
Under, "Excluding Entries"

"This will explicitly include this specie." Should be species

Also, the "Excluding Entries" header font is smaller than Filtering or Sort, is this intended? Is it a subtopic of "filtering"? I can't tell.

**Comment by ErinBecker** [comment]
@cmacdonell The "excluding entries" section is meant to be a sub-section within filtering, so I think the font size makes sense there. Typo fixed with #104
