### ISSUE TITLE
Fix "Sorting by multiple columns." 02-filter-exclude-sort

### ISSUE THREAD

**Issue by cmacdonell** [datacarpentry/OpenRefine-ecology-lesson#75]
Two fixes:

1. Remove the period at the end of the header
2. To me, the first challenge "Try sorting by a year after you have sorted by month. What happens to ordering?" is not clear. As well the second sentence should read "What happens to the ordering?"

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/127
