### ISSUE TITLE
Explain how sorting is different in OpenRefine in 02-filter-exclude-sort

### ISSUE THREAD

**Issue by cmacdonell** [datacarpentry/OpenRefine-ecology-lesson#76]
In OpenRefine, sorting does not change the data order itself, which is different than sorting in most spreadsheet programs. Under the **Sort >** menu there is an option to "Reorder rows permanently" if you wish to change the order. I think this is worth explaining in the lesson.

**Comment by Repositorian** [comment]
Agreed. Perhaps explain that sorting in OpenRefine takes two forms:

1/ Sort values as a visual aid (temporary display of records)
2/ Sort values to reorder records permanently

**Comment by villanueval** [comment]
Closing as stale issue.

**Comment by bencomp** [comment]
I feel this is worth keeping open and addressing.
