### ISSUE TITLE
Inconsistent use of OpenRefine vs Refine

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#78]
Episodes seem to use "OpenRefine" and "Refine" interchangeably. This could be confusing for learners and should be standardized.

**Comment by Repositorian** [comment]
Agree on this point.  There are still references to google refine in this lesson (eg in the install instructions) which is confusing. 

Also, with the first mention of OpenRefine, would it help to clarify that the IDE version is RefinePro?

**Comment by ErinBecker** [comment]
@Repositorian I'm not sure that mentioning RefinePro will help with clarity here. I hadn't heard of RefinePro before your comment, but when I looked at their website it appears to be a paid service based on OpenRefine. Is that accurate? Maybe add RefinePro to the last module (about additional resources) if you think it would help the learner, although I don't know how many of them are going to use the paid service.

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/97 but see comment above.
