### ISSUE TITLE
Unable to reproduce expected error when splitting cells

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#87]
The instructor notes, under "Split / Leading - Trailing Whitespace / Undo - Redo" says: 

"This will reveal an error in a few names that have spaces at the beginning (so-called leading white space)."

I've never been able to reproduce this error. Can someone confirm that the data file does in fact include leading white space?

**Comment by Repositorian** [comment]
So I just did a transform->common transforms->remove leading/trailing white space on the Scientific name Column and got the message that the transform operated on three cells in that column. 

Before running the transform, the Scientific name column faceted to 28 choices but after the transform it faceted to 26 choices. So apparently the whitespaces made two variant names collapse into a third one!

**Comment by ErinBecker** [comment]
Thanks @Repositorian, it looks like this works fine now. I don't know what I was doing wrong before. . .
