### ISSUE TITLE
Problems running from a network share at Windows

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/OpenRefine-ecology-lesson#96]
During https://anenadic.github.io/2017-03-30-manchester/, OpenRefine crashed when we try to launch it from a network share drive.

# Solution

1. Copy the OpenRefine folder to a local drive **not mapped to a network share**, e.g. "C:\Users\JaneDoe".
2. Open cmd, e.g. Windows black screen.
3. Change the working directory to the OpenRefine folder at "C:\Users\JaneDoe".
4. Run `openrefine.exe`.

For unknown reason, double clicking on `openrefine.exe` at the local drive also result in crash but calling from the command line doesn't.

# Upstream status

This bug was reported before at https://github.com/OpenRefine/OpenRefine/issues/1004.

# Possible instructors with more information

cc @anenadic @karawoo

**Comment by ErinBecker** [comment]
@rgaiacs Thanks for reporting this. I'll add it to the instructor notes under potential problems.
